prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings                         # 추가 1
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls')), # shop에 있는 urls로 떠넘기겠다는 의미(shop/ 까지는 끝내고 나머지 부분을 넘김!)
    path('weblog/', include('blog.urls')),  # blog에 있는 urls로 떠넘기겠다는 의미(blog/ 까지는 끝내고 나머지 부분을 넘김!)
    path('pizzas/', include('pizzas.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # db에 있는 media 파일 사진의 깨짐을 없애기 위해

if settings.DEBUG:                                       # 추가 2
    import debug_toolbar                                 # 추가 2
    urlpatterns += [                                     # 추가 2
        path('__debug__/', include(debug_toolbar.urls)), # 추가 2
    ]                                                    # 추가 2

shop/urls.py
from django.urls import path, register_converter
from shop import views  # shop에 있는 views를 갖고 옴
# from . import views  # . : 같은 폴더
from shop import converters

app_name = 'shop'

register_converter(converters.FourDigitYearConverter, 'yyyy')

urlpatterns = [
    path('excel/', views.response_excel, name='response_excel'),
    path('image/', views.response_image, name='response_image'),
    path('mysum/<int:x>/<int:y>/', views.my_sum, name='my_sum'),
    path('archives/<yyyy:year>/', views.year_archive, name='year_archive'),
    path('', views.item_list, name='item_list'), # 넘어온 게 아무것도 안 남아있으면 item_list를 보여주겠다는 의미
    path('<int:pk>/', views.item_detail, name='item_detail'),
    path('test_templates/', views.test_templates, name='test_templates'),
]

shop/models.py
from django.db import models
from pytz import timezone  # 현지 시각 출력을 위하여
from django.conf import settings
from django.urls import reverse

def local_time(input_time):
    fmt = '%Y-%m-%d %H:%M'
    my_zone = timezone(settings.TIME_ZONE)
    my_local_time = input_time.astimezone(my_zone)
    return my_local_time.strftime(fmt)

class Item(models.Model) :
    name = models.CharField(max_length=20)
    desc = models.TextField(blank=True)
    photo = models.ImageField()  # blank=True 지정하지 않은 경우
    created_at = models.DateTimeField(auto_now_add=True) # 데이터가 등록(추가)된 시간을 자동으로 지정해 줌
    updated_at = models.DateTimeField(auto_now=True)  # 현재 시각을 자동으로 넣어 줌  // 여기까지 하고 makemigrations 후 migrate
    tags = models.ManyToManyField('Tag', blank=True, related_name='tags')  # tag_set 아니고, tags

    class Meta:
        ordering = ['-id']  # Item 객체의 기본 정렬 순서 지정(최근 것 먼저)

    def __str__(self): # __str__() 함수를 만들면 객체를 만들 때 기본적으로 뭘 보여줄지를 지정 가능 # str 지정 안하면 object 1 이런식으로 나옴
        return self.name

    def short_desc(self):
        if self.desc:
            t = self.desc[:20] + '...'   # desc 속성의 일부만 반환
        else:
            t = '(내용 없음)'
        return t
    short_desc.short_description = '간략 내용'

    def tagged(self):
        ts = self.tags.all()
        return '{' + ', '.join(map(str, ts)) + '}'
    tagged.short_description = '태그 집합'
    # 클래스 메소드로 속성을 대신할 때, verbose_name 대신에 short_description

    def updated(self):
        return local_time(self.updated_at)
    updated.short_description = '수정 일시'

    def get_absolute_url(self):
        return reverse('shop:item_detail', kwargs={'pk': self.pk})


# 리뷰라는 클래스 만들고 Item과 일대다로 만들어 보기
class Review(models.Model):  # Review라고 지었지만 admin 화면에선 Reviews로 나옴
    item = models.ForeignKey(Item, on_delete=models.CASCADE,
                             related_name='reviews', verbose_name='상품')  # 장고 2.x 버전부터 on_delete는 꼭 밝혀야 함
    message = models.TextField('리뷰')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-item__id', '-id']  # '-post__id', '-id'

    def __str__(self):  # __str__() 함수를 만들면 객체를 만들 때 기본적으로 뭘 보여줄지를 지정 가능
        return self.message

    def updated(self):
        return local_time(self.updated_at)
    updated.short_description = '수정 일시'


class Tag(models.Model):
    name = models.CharField('태그', max_length=100, unique=True)

    class Meta:
        ordering = ['-id']  # Tag 객체의 기본 정렬 순서 지정

    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404
from shop.models import Item, Tag
# from .models import Item # 같은 폴더에 있는 models를 가져오라는 의미
from django.http import HttpResponse
import requests
from io import BytesIO
from PIL import Image, ImageDraw, ImageFont
import pandas as pd                           # 엑셀 요청 처리
from urllib.parse import quote

def response_excel(request):
    df = pd.DataFrame([
        [100, 110, 120],
        [200, 210, 220],
    ])

    io = BytesIO()
    df.to_excel(io)
    io.seek(0)

    encoded_filename = quote('pandas.xlsx')     # '.xls'가 아니라 '.xlsx'
    response = HttpResponse(io, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = \
        "attachment; filename*=utf-8''{}".format(encoded_filename)
    return response

def response_image(request):
    ttf_path = 'C:/Windows/Fonts/malgun.ttf'  # 윈도우, 맥: '/Library/Fonts/AppleGothic.ttf'

    # 이미지 파일 다운로드 혹은 로컬 디스크 상의 이미지 직접 열기
    image_url = 'http://www.flowermeaning.com/flower-pics/Calla-Lily-Meaning.jpg'
    res = requests.get(image_url)  # 서버로 HTTP GET 요청하여, 응답 획득
    io = BytesIO(res.content)  # 응답의 Raw Body 메모리 파일 객체 BytesIO 인스턴스 생성
    io.seek(0)  # 파일의 처음으로 커서를 이동

    canvas = Image.open(io).convert('RGBA')  # 이미지 파일을 열고, RGBA 모드로 변환
    font = ImageFont.truetype(ttf_path, 40)  # 지정 경로의 TrueType 폰트, 폰트 크기40
    draw = ImageDraw.Draw(canvas)  # canvas에 대한 ImageDraw 객체 획득

    text = 'Smart IT, by logistex'
    left, top = 300, 400
    margin = 10
    width, height = font.getsize(text)
    right = left + width + margin
    bottom = top + height + margin
    draw.rectangle((left, top, right, bottom), (255, 255, 224))
    draw.text((left+5, top+5), text, font=font, fill=(20, 20, 20))

    response = HttpResponse(content_type='image/png')
    canvas.save(response, format='PNG')  # HttpResponse의 유사 파일 객체 특성 활용
    return response

def year_archive(request, year):
    if year is not None:
        return HttpResponse('{}년도 자료입니다.'.format(year))
    else:
        return HttpResponse('해당 연도 자료는 없습니다.')

def my_sum(request, x, y):
    result = x + y
    output = '{} = {} + {}'.format(result, x, y)
    return HttpResponse(output)

def item_list(request):  # 함수 기반 뷰
    items = Item.objects.all()
    # return render(  # 뷰가 하는 가장 중요한 일 # render를 부르면 최종적으론 HttpResponse가 작동
    #     request,                     # 요청 정보(요청한 사람의 ip 주소, 브라우저의 종류 등등)
    #     'shop/item_list.html',   # 템플릿 이름
    #     {'item_list' : items}      # 템플릿에 전달할 정보를 사전 형태로
    # )
    # request.GET 객체에게 키 값이 'q'로 지정된 값을 요구해서 변수 q에 저장
    q = request.GET.get('q', '')  # 키 값이 'q'로 지정된 값이 없으면 None이 반환됨
    if q: # q가 널 아니면 qs에 filter 조건 추가
        items = items.filter(name__icontains=q)
    return render(request, 'shop/item_list.html', {
        'item_list': items,
        'q': q,
    })

def item_detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    all_tag = Tag.objects.all()
    mystr = item.tagged()
    my_tag = {}
    for t in all_tag:
        # mystr에서 t.name을 발견한 위치를 my_tag 사전에 등록
        # 키는 t.name으로, 값은 (못 찾으면 -1, 찾으면 양수)
        my_tag[t.name] = str(mystr).find(t.name)
    return render(request, 'shop/item_detail.html',
                  {'item': item, 'my_tag': my_tag})

class MyClass:
    x = 10
    y = 20

def test_templates(requset):
    from django.template import Context, Template
    import datetime       # USE_TZ = True
    from django.utils import timezone   # TIME_ZONE = 'Asia/Seoul'
    from dateutil.parser import parse

    # 맥락 변수 사전
    my_dict = {'first_name': 'haewoong', 'last_name': 'Shin'}
    my_obj = MyClass()
    my_list = [1, 2, 3, 4]
    my_date = datetime.datetime.now()
    local_time = timezone.localtime()
    my_b_date1 = datetime.date(2019, 12, 29)
    my_b_date2 = parse('2010-12-29')
    my_b_datetime = datetime.datetime(2010, 12, 29, 17, 34, 56)
    my_string = '사랑하지 않으려면 떠나라. Love it or leave it.'

    context = Context({'my_dict': my_dict, 'my_obj': my_obj, 'my_list': my_list,
                       'my_date': my_date, 'local_time': local_time,
                       'my_b_date1': my_b_date1, 'my_b_date2': my_b_date2,
                       'my_b_datetime': my_b_datetime, 'my_string': my_string,
                       })
    template = Template(
        "사전 < my_dict.last_name >: {{ my_dict.last_name }} <br/>"
        + "객체 < my_obj.x >: {{ my_obj.x }} {{ my_obj.y }} <br/>"
        + "리스트 < my_list.0 >: {{ my_list.0 }} {{ my_list.2 }}: {{ my_list.2 }} <br/>"
        + "< my_dict.first_name|title >: {{ my_dict.first_name|title }} <br/>"
        + "{% verbatim myblock %}{% now 'Y-m-d H:i:s' %}"
        + "{% endverbatim myblock %} : {% now 'Y-m-d H:i:s' %} <br/>"
        + "< my_date > : {{ my_date }} <br/>"
        + "< local_time >: {{ local_time }} <br/>"
        + "< my_b_date1 >: {{ my_b_date1 }} <br/>"
        + "< my_b_date2 >: {{ my_b_date2 }} <br/>"
        + "< my_b_date1|date:'SHORT_DATE_FORMAT' >: {{ my_b_date1|date:'SHORT_DATE_FORMAT' }} <br/>"
        + "(마지막에 점이 찍힘!! 필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>"
        + "< my_b_date1|date:'Y년 m월 d일' >: {{ my_b_date1|date:'Y년 m월 d일' }} <br/>"
        # + "< my_b_date|date:'LONG_DATE_FORMAT' >(???)': {{ my_b_date|date:'LONG_DATE_FORMAT' }} <br/>"
        # + "(필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>" # 오류!!
        + "< my_b_datetime >: {{ my_b_datetime }} <br/>"
        + "< my_b_datetime|date:'Y년 m월 d일' > < my_b_datetime|time:'H시 i분 s초' >: "
        + "{{ my_b_datetime|date:'Y년 m월 d일' }}  {{ my_b_datetime|time:'H시 i분 s초' }} <br/>"
        + "(필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>"
        + "< my_string|lower|truncatewords:'4' >: {{ my_string|lower|truncatewords:'4' }} <br/>"
        # 수업 규칙 : 숫자 앞뒤에 불필요한 따옴표는 안하기로 정함!
        + "< my_string|lower|truncatewords:4 >: {{ my_string|lower|truncatewords:4 }} <br/>"
        + "(필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>"
        + "< my_string|lower|truncatechars:'12' >: {{ my_string|lower|truncatechars:'12' }} <br/>"
        +"(필터 내부에서 인수를 표시할 때 사용하는 \':\' 뒤에 띄우지 말 것!)<br/>"
    )
    content = template.render(context)

    return HttpResponse(content)

shop/templates/shop/item_detail.html
{% extends './layout.html' %}
{% load static %}

{% block content %}
    <a href="{% url 'shop:item_list' %}">상품 목록으로 돌아가기</a><br/><br/>

    <table>
        <thead>
            <th>필드</th>
            <th>내용</th>
        </thead>
        <tbody>
            <tr>
                <td width="10%">번호:</td>
                <td>{{ item.id }}</td>
            </tr>
            <tr>
                <td>제품명:</td>
                <td>{{ item.name }}</td>
            </tr>
            <tr>
                <td>요약정보:</td>
                <td>{{ item.short_desc }}</td>
            </tr>
            <tr>
                <td>이미지:</td>
                <td>{% if item.photo %}<img src="{{ item.photo.url }}" />{% endif %}</td>
            </tr>
            <tr>
                <td>상세정보:</td>
                <td>{{ item.desc|linebreaksbr }}</td>
            </tr>
            <tr>
                <td>게시 일시:</td>
                <td>{{ item.created_at }}</td>
            </tr>
            <tr>
                <td>수정 일시:</td>
                <td>{{ item.updated }}</td>
            </tr>
            <tr>
                <td>태그:</td>
                <td>{{ item.tagged }}</td>
            </tr>
        </tbody>
    </table>

    <br/><br/><hr><br/><br/>

    <table>
        <thead>
            <th>id</th>
            <th>상품평</th>
            <th>작성 일시</th>
            <th>수정 일시</th>
        </thead>
        <tbody>
            {% for c in item.reviews.all %}
                <tr>
                    <td>{{ c.id }}</td>
                    <td>{{ c.message|linebreaksbr }}</td>
                    <td>{{ c.created_at }}</td>
                    <td>{{ c.updated }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

shop/templates/shop/item_list.html
<!-- shop/templates/shop/item_list.html -->
{% extends './layout.html' %}
{% load static %}

{% block content %}
    {{ block.super }}
    <form action="" method="GET">
        <input type="text" name="q" value="{{ q }}" />
        <input type="submit" value="검색" />
    </form>
    <hr>
    <table>
        <thead>
            <th>번호</th>
            <th>이름</th>
            <th>설명</th>
            <th>사진</th>
            <th>등록 일시</th>
            <th>수정 일시</th>
        </thead>
        <tbody>
            {% for item in item_list %}
            <tr>
                <td> {{ item.id }} </td>
                <td>
                    <a href="{{ item.get_absolute_url }}">
                    <!--<a href="/shop/{{ item.pk }}">-->
                        {# href="shop/..."로 하면 오류!!! #}
                        {{ item.name }}
                    </a>
                </td>
                <td> {{ item.desc }} </td>
                <td> {{ item.photo }} </td>
                <td> {{ item.created_at }} </td>
                <td> {{ item.updated_at }} </td>
            </tr>
            {% endfor %}
        </tbody>
    </table> <br/><br/>

{#    {{ request }} <br/>#}
{#    request.method: {{ request.method }} <br/>#}
{#    request.GET: {{ request.GET }} <br/>#}
{#    request.META: {{ request.META }}#}
    <hr/>
    {{ item_list }}
    <hr>
    {% for item in item_list %}
        {{ item }} <br>
    {% endfor %}
    <hr>
    {% for item in item_list %}
        {{ item.name }} #
        {{ item.desc }} #
        {{ item.photo }} #
        {{ item.created_at }} #
        {{ item.updated_at }} <br/>
        {% if item.photo %}
            <img src="{{ item.photo.url }}" />
        {% endif %} <br/>
    {% endfor %}
{% endblock %}

shop/templates/shop/layout.html
<!-- shop/templates/shop/layout.html -->
{% extends '../layout.html' %}

{% load static %}

{% block title %}
    {{ block.super }} shop
{% endblock %}

{% block extra_head %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'shop/shop.css' %}" />
{% endblock %}

{% block content %}
    {{ block.super }}
    <img src="{% static 'shop/com_shin.png' %}" alt="shop logo image">
    <h2>shop in logistex site </h2>
{% endblock %}

{% block extra_body %}
    {{ block.super }}
    <script src="{% static 'shop/shop.js' %}"></script>
{% endblock %}